### PR TITLE
General updates

### PR DESCRIPTION
**Pull request by comet0**
Note: 2nd Aug 2016, not ready for merge yet.

### CODE REVIEW

**Comment by Ness199X** [comment]
Oh you are still alive, I've been hopping in the IRC every couple of days for the last month but you and evemoo haven't been on. Do you have a new communication method?

**Comment by comet0** [comment]
evemoo set up http://evemu.forumotion.com/ but he is currently getting drunk during summer.

Was thinking about setting up a discord channel(?) as a less formal means of communication while fixing stupid little bugs.

**Comment by Ness199X** [comment]
Somehow I knew you were gonna say Discord. I have some issues with Discord but its better than the IRC since we all seem to occupy different timezones,

Also the forum emails you your password in plaintext, that was an unpleasant surprise.

**Comment by comet0** [comment]
What issues do you have? 
Got any other ideas, not too fond of it myself due to it being hosted.

**Comment by Ness199X** [comment]
Mostly that it's hosted, it's been extremely buggy recently, and the developers have been prioritizing "flashy" features over heavily requested stuff like search.

For on site options you have Mattermost which is buggy as hell, or Rocket.Chat, which I haven't used.

Really the best thing may be to just use IRC with a logger bot with public logs

**Comment by comet0** [comment]
What about a 'chatbox' on the forum site? 
Just enabled it, if you have made your account give it a try here
http://evemu.forumotion.com/chatbox/index.forum?

**Comment by comet0** [comment]
There is the IRC with some form of archival script running, i might be able to throw something together so that while a bot is connected it is archiving all chat logs onto a simple website

**Comment by Ness199X** [comment]
The chatbox doesn't seem to work. And its buried. I think Discord isn't a terrible stopgap for awhile, if we get things back into swing we can look at another option.

**Comment by comet0** [comment]
https://discord.gg/WtjEMUr

Just set it up, will do for quick questions and dev talk

**Comment by comet0** [comment]
Just a note to anybody compiling on Arch linux, 
you probably need this diff to allow evemu to compile

https://gist.github.com/comet0/53bd08f9177ff8f0883537dde790d5c2

**Comment by eve-moo** [comment]
Well, I'm starting to come back.  I'll trust that nothing in this pull request breaks anything.  I've looked through it but haven't tried compiling it.  Need to set up a new development system as my old one died... :(

**Pull request merged**
